//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica1para
{
    using System;
    using System.Collections.Generic;
    
    public partial class Osnovnaya
    {
        public int ID_Osnovnaya { get; set; }
        public int Client_ID { get; set; }
        public string PlaceTatu { get; set; }
        public int PriceMaterials { get; set; }
        public int PriceUslugi { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
